export function renderExternalPaymentScreen({ state, webPayment, subscription }) {
  const statusText = webPayment.status === 'creating' ? 'Создаётся платёжная ссылка…' : webPayment.status === 'waiting_return' ? 'Оплатите на сайте и затем вернитесь в приложение.' : webPayment.status === 'synced' ? 'Доступ обновлён с сервера.' : webPayment.status === 'failed' ? (webPayment.lastError || 'Не удалось выполнить действие.') : 'Оплата проходит на внешнем сайте. После оплаты доступ обновится через аккаунт.';
  const accessText = webPayment.access === 'premium' || subscription.status === 'active' ? 'Премиум-доступ активен' : 'Сейчас активен базовый доступ';
  const chipClass = webPayment.status === 'failed' ? 'error' : webPayment.status === 'synced' ? 'success' : 'neutral';
  return `
    <section class="screen ${state.route === 'externalPayment' ? 'active' : ''}" data-screen="externalPayment">
      <div class="card glass-card inner-hero-card"><div class="screen-hero-art subscription-hero-art"></div><div class="section-overline">Web Checkout</div><h2 class="section-title premium-screen-title">Оплата на сайте</h2><p class="section-sub premium-screen-sub">Главный внешний маршрут оплаты с возвратом доступа через аккаунт.</p></div>
      <div class="card glass-card info-panel-card two-info-grid"><div class="item premium-info-item"><div class="item-title">Статус</div><div class="muted small">${statusText}</div><div style="margin-top:10px;"><span class="status-chip ${chipClass}">${webPayment.status || 'idle'}</span></div></div><div class="item premium-info-item"><div class="item-title">Доступ</div><div class="muted small">${accessText}</div><div style="margin-top:10px;"><span class="status-chip ${accessText.includes('активен') ? 'success' : 'neutral'}">${accessText.includes('активен') ? 'premium active' : 'basic active'}</span></div></div></div>
      <div class="card answer-card action-list-card"><div class="status-panel"><div class="state-icon ${webPayment.status === 'creating' || webPayment.status === 'waiting_return' ? 'state-loading' : 'state-sync'}"></div><div><div class="status-panel-title">Checkout State</div><div class="muted small">${statusText}</div></div></div><div class="list premium-action-list" style="margin-top:14px;"><button class="item premium-action-item" data-web-plan="monthly"><div class="item-title">План на месяц</div><div class="muted small">Основной внешний платёжный маршрут.</div></button><button class="item premium-action-item" data-web-plan="family"><div class="item-title">Семейный план</div><div class="muted small">Для будущего семейного доступа.</div></button></div><div class="row" style="margin-top:14px;"><button class="primary primary-wide" data-stub-action="create-web-checkout">Перейти к оплате</button><button class="secondary" data-stub-action="open-web-checkout">Открыть ссылку</button><button class="secondary" data-stub-action="refresh-web-access">Обновить доступ</button><button class="secondary" data-nav="subscription">Назад</button></div></div>
    </section>`;
}
