export function renderStoreBillingScreen({ state, purchaseFlow, products = [] }) {
  const statusText = purchaseFlow.status === 'loading' ? 'Идёт оформление покупки…' : purchaseFlow.status === 'restoring' ? 'Идёт восстановление покупки…' : purchaseFlow.status === 'success' ? 'Последнее действие выполнено.' : purchaseFlow.status === 'failed' ? (purchaseFlow.lastError || 'Действие не выполнено.') : 'Выберите план и продолжите.';
  const chipClass = purchaseFlow.status === 'failed' ? 'error' : purchaseFlow.status === 'success' ? 'success' : 'neutral';
  return `
    <section class="screen ${state.route === 'storeBilling' ? 'active' : ''}" data-screen="storeBilling">
      <div class="card glass-card inner-hero-card"><div class="screen-hero-art subscription-hero-art"></div><div class="section-overline">Store Billing</div><h2 class="section-title premium-screen-title">Покупка в магазине</h2><p class="section-sub premium-screen-sub">Каталог планов, покупка и восстановление доступа через App Store или Google Play.</p></div>
      <div class="card glass-card info-panel-card"><div class="status-panel"><div class="state-icon ${purchaseFlow.status === 'loading' || purchaseFlow.status === 'restoring' ? 'state-loading' : purchaseFlow.status === 'success' ? 'state-sync' : 'state-empty'}"></div><div><div class="status-panel-title">Состояние покупки</div><div class="muted small">${statusText}</div><div style="margin-top:10px;"><span class="status-chip ${chipClass}">${purchaseFlow.status || 'idle'}</span></div></div></div></div></div>
      <div class="card answer-card action-list-card"><div class="list premium-action-list">${products.map(product => `<button class="item premium-action-item" data-plan-select="${product.key}"><div class="item-title">${product.title}</div><div class="muted small">${product.priceLabel}</div></button>`).join('') || `<div class="premium-empty-state"><div class="state-icon state-empty"></div><div><div class="item-title">Планы загрузятся позже</div><div class="muted small">Список товаров появится после подключения реального магазина.</div></div></div>`}</div><div class="row" style="margin-top:14px;"><button class="primary primary-wide" data-stub-action="start-store-purchase">Оформить покупку</button><button class="secondary" data-stub-action="restore-store-purchase">Восстановить покупку</button><button class="secondary" data-nav="subscription">Назад</button></div></div>
    </section>`;
}
