export function renderSubscriptionScreens({ state, subscription }) {
  const subStateText = subscription.status === 'active' ? `Текущий статус: активна (${subscription.plan || 'план'})` : subscription.status === 'grace' ? 'Текущий статус: льготный период' : 'Текущий статус: не подключена';
  const premiumState = subscription.status === 'active' ? 'Premium' : subscription.status === 'grace' ? 'Grace' : 'Basic';
  return `
    <section class="screen ${state.route === 'subscription' ? 'active' : ''}" data-screen="subscription">
      <div class="card glass-card inner-hero-card"><div class="screen-hero-art subscription-hero-art"></div><div class="section-overline">Access Matrix</div><h2 class="section-title premium-screen-title">Подписка и доступ</h2><p class="section-sub premium-screen-sub">Тарифы, внешний платёж, покупки через магазин и состояние премиального контура.</p><div class="hero-status-row profile-status-grid"><div class="hero-status-pill"><span>Статус</span><b>${premiumState}</b></div><div class="hero-status-pill"><span>Режим</span><b>${subscription.plan || 'Base Plan'}</b></div></div></div>
      <div class="card glass-card stat-strip dual-strip"><div class="premium-stat"><span class="premium-stat-label">Подписка</span><b>${subscription.status === 'active' ? 'Активна' : 'Не подключена'}</b></div><div class="premium-stat"><span class="premium-stat-label">Контур</span><b>${subStateText.replace('Текущий статус: ', '')}</b></div></div>
      <div class="card answer-card action-list-card"><div class="list premium-action-list"><div class="item premium-action-item passive-item"><div class="item-title">Базовый доступ</div><div class="muted small">Демо-режим без реальной оплаты. Позже здесь будут лимиты и уровни доступа.</div></div><button class="item premium-action-item" data-nav="externalPayment"><div class="item-title">Оплата на сайте</div><div class="muted small">Главный маршрут оплаты через внешний платёжный сервис.</div></button><button class="item premium-action-item" data-nav="plans"><div class="item-title">Планы</div><div class="muted small">Выбор тарифов, преимуществ и будущих семейных пакетов.</div></button><button class="item premium-action-item" data-nav="billing"><div class="item-title">Покупка через магазин</div><div class="muted small">Маршрут App Store / Google Play для реальной подписки.</div></button><button class="item premium-action-item" data-nav="storeBilling"><div class="item-title">Оплата и покупки</div><div class="muted small">История покупок, способы оплаты и восстановление доступа.</div></button></div></div>
    </section>

    <section class="screen ${state.route === 'plans' ? 'active' : ''}" data-screen="plans">
      <div class="card glass-card inner-hero-card compact-hero-card"><div class="screen-hero-art subscription-hero-art"></div><div class="section-overline">Plans</div><h2 class="section-title premium-screen-title">Планы подписки</h2><p class="section-sub premium-screen-sub">Базовая сцена выбора тарифов. Позже здесь появятся реальные пакеты и различия по функциям.</p></div>
      <div class="card answer-card action-list-card"><div class="list premium-action-list"><div class="item premium-action-item"><div class="item-title">Месяц</div><div class="muted small">Основной план подписки. Точка для будущей реальной монетизации.</div></div><div class="item premium-action-item"><div class="item-title">Семейный доступ</div><div class="muted small">Позже здесь будет семейный пакет с несколькими детьми.</div></div></div><div class="row" style="margin-top:14px;"><button class="primary primary-wide" data-stub-action="plans-submit">Продолжить</button><button class="secondary" data-nav="subscription">Назад</button></div></div>
    </section>

    <section class="screen ${state.route === 'billing' ? 'active' : ''}" data-screen="billing">
      <div class="card glass-card inner-hero-card compact-hero-card"><div class="screen-hero-art subscription-hero-art"></div><div class="section-overline">Billing</div><h2 class="section-title premium-screen-title">Оплата и покупки</h2><p class="section-sub premium-screen-sub">Системный экран для способа оплаты и восстановления доступа.</p></div>
      <div class="card answer-card action-list-card"><div class="list premium-action-list"><div class="item premium-action-item"><div class="item-title">Способ оплаты</div><div class="muted small">Будет подключён позже вместе с реальной подпиской.</div></div><div class="item premium-action-item"><div class="item-title">Восстановить покупку</div><div class="muted small">Кнопка для App Store / Google Play будет подключена в финале.</div></div><button class="item premium-action-item" data-stub-action="deactivate-subscription"><div class="item-title">Отключить демо-подписку</div><div class="muted small">Сброс демо-состояния подписки.</div></button></div><div class="row" style="margin-top:14px;"><button class="secondary" data-stub-action="restore-purchase">Восстановить</button><button class="secondary" data-nav="subscription">Назад</button></div></div>
    </section>`;
}
